Complete the about-me section
KenbonTN/Portfolio-1 pull request #2
Opened 2023-01-12 14:33 UTC by KenbonTN

- [ ] No linter error.
- [ ] README file is more descriptive.
- [ ] I used CSS Grid and Flexbox combined.
- [ ] Implemented the button interactions.

2023-01-12 15:53 UTC, osamaashraf6 requested changes
Hi @KenbonTN 😊, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Not linter errors present
- Good descriptive pull request

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 15:53 UTC, osamaashraf6 commented on index.html
> +                            <li class="Job-title_and_year">
- [ ] Kindly consider the container of the works section is a section tag and for each project using a div tag.

2023-01-12 15:53 UTC, osamaashraf6 commented on index.html
> +                    </h2>
- [ ] For each project there is only on h2 tag not two h2 tags

2023-01-12 15:53 UTC, osamaashraf6 commented on index.html
> +                </section>
- [ ] Kindly fix the design for each project and make sure to match your design with the Figma design and use appropriate padding and margin.

| Figma design | Your design| 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/83360636/212107124-25bcaeae-49aa-414e-b660-e7fba0242ba5.png) |  ![image](https://user-images.githubusercontent.com/83360636/212106634-bdbffd0f-8b3d-4c61-8052-c2f854664912.png)  |

2023-01-12 15:53 UTC, osamaashraf6 commented on index.html
> +                                </svg>
- [ ] Kindly use the correct icon for LinkedIn like the Figma design, you can export it from Figma and use it 

| Figma design | Your design| 
| --- | --- |
|   ![image](https://user-images.githubusercontent.com/83360636/212112534-551d7cd0-2a3a-4e47-abb0-71596f600579.png)   |   ![image](https://user-images.githubusercontent.com/83360636/212112639-09f943e4-1d94-44db-9236-0c497ca17bff.png)    |

2023-01-12 15:53 UTC, osamaashraf6 commented on styles/mobile-first-style.css
> +}
- [ ] Kindly use the appropriate margin like in the design in the Figma template

| Figma design | Your design| 
| --- | --- |
|   ![image](https://user-images.githubusercontent.com/83360636/212113850-71977aec-621f-4777-9cdd-0dd2a9d5076d.png)   |   ![image](https://user-images.githubusercontent.com/83360636/212113713-d2ccc933-2ff5-46a6-820a-8afa832ab2a3.png)    |

2023-01-12 15:53 UTC, osamaashraf6 commented on index.html
> +                <section class="languages">
- [ ] Kindly consider the technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li`

2023-01-14 20:11 UTC, algerina approved these changes
Hi @KenbonTN ,
Good job so far! 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
You did great implementing the previews TSE's requirements :+1: 
Your project is complete!  It's time to merge it :shipit:

<img src="https://media2.giphy.com/media/artj92V8o75VPL7AeQ/giphy.gif"/>

 
 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-01-14 20:11 UTC, algerina commented on index.html
>                                      </a>
- [ Optional] Your Linkedin icon is not displayed correctly kindly, replace the link with the following `<img src="./images/Linkedin icon.svg" alt="Linkedin icon">`

2023-01-14 20:17 UTC, merged